### ISSUE TITLE
Second pane doesn't execute configured command

### ISSUE THREAD

**Issue by philippbosch** [timolins/hyperlayout#24] opened 2017-01-26 08:45 UTC
I'm using the most basic `.hyperlayout` config:

```json
[
  [
    "echo 'Hello'",
    "echo 'World'"
  ]
]
```

If I run `hyperlayout` it creates a second pane, runs the `echo "Hello"` command in the first pane but nothing in the second one. See this:

![kapture 2017-01-26 at 9 40 18](https://cloud.githubusercontent.com/assets/57509/22324869/c625ea20-e3ab-11e6-8866-bdf10a7b8f9a.gif)

- hyper version: 1.1.0
- hyperlayout version: 0.2.1
- Shell: zsh

Any idea what's wrong here?

**Comment by timolins** [comment] 2017-01-26 12:54
Oh no. This was/is a known issue (#15). `0.2.1` should have fixed this issue (at least it did for me, and for other users as well), but this isn't the case for everyone as it seems. I can't reproduce this error on my machine (also macOS, Hyper 1.1, hyperlayout 0.2.1), which makes it hard for me to debug. Maybe there is something odd showing up in the Hyper console?

**Comment by philoserf** [comment] 2018-01-06 06:17
The issue is resolved in the current release. Just need to mark this issue and close, I think.

**Comment by timolins** [comment] 2018-01-09 19:16
I'm not sure if anyone is still facing this problem. I will close this issue for now. Let me know me know if someone is still affected. 

_@philoserf, thanks for all comments & thoughts_

**Closed by timolins** 2018-01-09 19:16 UTC
